1.   setup:
2. -name:
3.   a new ".yaml dev.envro" file
4.     build:
3.       -name:
4.    a new "PROPRE_CI_PIPELINE"
5.  -stage:
6.    -name:
7.  a new "PROPRE_CI,_PIPELINE.zip" file:
8. run job(s):
9.  -name:
10. as a new dotenvro emmiter file [/storage/emulated/0/Files by Google/Compressed files/cybersecaws.yml.zip]
11. -name:
12. "PROPRE_CI_PIPELINE"
13. run job(s):
14. name:
15. -merge commit(s)
16. -name(s):
17. ["kenaimarcel"],
18. ["MarcelMonde"] to -repo
19. run job(s):
20. name:
21. -deploy code to workflow:
22. push code: 
23. --force push 