1.   setup:
2. -name:
3.   a new ".yaml dev.envro" file
4.     build:
3.       -name:
4.    a new "PROPRE_CI_PIPELINE"
5.  -stage:
6.    -name:
7.   a new "PROPRE_CI,_PIPELINE.zip" file:
8. run job(s):
9.    -name:
10.    "PROPRE_CI_WORKFLOW": 
12. deploy code: 
13. -to anew dotenvro emmiter file /path/way.zip file:
14. -name:
  "/storage/emulated/0/Files by Google/Compressed files/cybersecaws.yml.zip"
15.    link:
16.      -name:
17.    "PROPRE_CI_PIPELINE"
18.   run job(s):
17. name(s):
18.   -merge:
19.  commit to -repo:
20.     -name(s):
21. ["kenaimarcel"],
22. ["MarcelMonde"] 
23.     run job(s):
24.   -push code: 
25. --force push 