name: Deploy AWS Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize Git repository
      run: git init

    - name: git add .zip file to repository
      run: -Add zip file [/path/path/to/cybersecaws.yml]
      
    - name: git extract .zip file path to a new configuration dev.envro file
      run: -convert zip path file to a new dotenvro configuration pipeline 

    - name: Set up environment configuration
      run: cp devcert.yml path/to/env

    - name: Build AWS CI pipeline
      run: echo "Building AWS CI pipeline (add actual commands here)"

    - name: Link AWS CI to environment file
      run: echo "Linking AWS CI pipeline to devcert.yml (add actual commands here)"

    - name: Merge branches
      run: 
        git add .zip file [path/to/cybersecaws.yml] zip file
        git checkout main
        git merge marcelmonde kenaimarcel

    - name: Deploy environment 
      run: echo "Deploying devcert.yml file using AWS pipeline (add actual commands here)"

    - name: Force push changes
      run: git push origin main --force
