name: Deploy AWS Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize Git repository
      run: git init

    - name: Add zip file to repository
      run: git add path/to/cybersecaws.yml.zip

    - name: Set up environment configuration
      run: cp devcert.yml path/to/env

    - name: Build AWS CI pipeline
      run: echo "Building AWS CI pipeline (add actual commands here)"

    - name: Link AWS CI to environment file
      run: echo "Linking AWS CI pipeline to devcert.yml (add actual commands here)"

    - name: Merge branches
      run: |
        git checkout main
        git merge marcelmonde kenaimarcel

    - name: Deploy environment file
      run: echo "Deploying devcert.yml file using AWS pipeline (add actual commands here)"

    - name: Force push changes
      run: git push origin main --force