name: Deploy AWS Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment configuration
      run: cp devcert.yml path/to/env

    - name: Build AWS CI pipeline
      run: echo "Building AWS CI pipeline (add actual commands here)"

    - name: Link AWS CI to environment file
      run: echo "Link to blank.CI pipeline to devcert.yml"

    - name: Merge branches
      run: zip file "[path/to/cybersecaws.yml.zip]" file

    - name: Deploy environment 
      run: echo "Deploying devcert.yml file using AWS pipeline (add actual commands here)"

    - name: Force push changes
      run: git push origin main --force
