name: Deploy AWS Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: AWS Pipeline
      uses: actions/checkout@v3

    - name: Set up a new dotenviro file
      run: blank.yml 

    - name: Build AWS CI pipeline
      run: echo "CI pipeline (add actual commands here)"

    - name: Link AWS CI pipeline to .envr file
      run: echo "blank.yml file as a new CI pipeline for blank.yml" file

    - name: Deploy environment 
      run: echo "Deployment blank.yml environment )"

    - name: Force push changes
      run: git push origin main --force
